// Auto-generated file - This file is now a consumer of the virtual module.
// It re-exports the component paths from the virtual module.

import { COMPONENT_PATHS as CPaths } from 'virtual:component-manifest';

/**
 * @type {Record<string, () => Promise<any>>}
 *
 * Defines the available components and their corresponding dynamic import functions.
 * This object is automatically generated by `vite-plugin-component-manifest`.
 *
 * - Keys are component tag names (e.g., 'home-page', 'about-page').
 * - Values are functions that, when called, return a Promise resolving to the component's module.
 *
 * This structure enables lazy loading of components, improving initial application load time.
 * The router uses this map to load components on demand based on the current route.
 *
 * Example (for illustration, actual paths are auto-generated):
 * ```
 * {
 *   'home-page': () => import('./components/home-page/home-page.ts'), // Dev mode
 *   'about-page': () => import('/assets/about-page.abcdef.js') // Prod mode
 * }
 * ```
 * **DO NOT EDIT THIS FILE DIRECTLY IF IT'S ONLY RE-EXPORTING.**
 * The actual paths are managed by `vite-plugin-component-manifest` via the virtual module.
 */
export const COMPONENT_PATHS = CPaths;

// Optional: Log to confirm the virtual module is working, can be removed later.
// console.log('src/components.ts loaded, COMPONENT_PATHS from virtual module:', COMPONENT_PATHS);
